#include<stdio.h>
int main()
{
    int m,n,count=0,i,j;
    scanf("%d",&m);
    scanf("%d",&n);
    for(i=m;i<=n;i++)
    {
        if(i==1)
        {
            continue;
        }
        else
        {
        count=0;
        for(j=2;j<i;j++)
        {
            if(i%j==0)
            {
                count++;
            }
        }
        if(count==0)
        {
            printf("%d
",i);
        }
        }
    }
}