#include<stdio.h>
int main()
{
    int n,i,j,k,p1=0,p2=0,c=0;
    scanf("%d",&k);
    while(k>0)
    {
        scanf("%d",&n);
        c=0;
        p1=0;
        p2=0;
        for(i=n;i>2;i--)
        {
            c=0;
            for(j=2;j<i;j++)
            {
                if(i%j==0)
                {
                    c=1;
                    break;
                }
            }
            if(c==0)
            {
                p1=i;
                break;
            }
        }
        for(i=n;i<n+100;i++)
        {
            c=0;
            for(j=2;j<i;j++)
            {
                if(i%j==0)
                {
                    c=1;
                    break;
                }
            }
            if(c==0)
            {
                p2=i;
                break;
            }
        }
        if(n-p1<=p2-n)
        {
            printf("%d
",p1);
        }
        else
        {
            printf("%d
",p2);
        }
        k--;
    }
    return 0;
}