#include<stdio.h>
int main()
{
    int n,m,s,i,r,res=0,x;
    scanf("%d",&m);
    s=1;
    for(n=m+1;n<=100000;n++)
    {
        s=1;
        for(i=2;i<=n/2;i++)
        {
            if(n%i==0)
            {
                s=0;
                break;
            }
        }
        if(s==1)
        {
            res=0;
            x=n;
            while(x>0)
            {
                r=x%10;
                res=(res*10)+r;
                x=x/10;
            }
            if(res==n)
            {
                printf("%d",n);
                break;
            }
        }
    }
}